namespace KegID.Model
{
    public enum ViewTypeEnum
    {
        AddPartnerView,
        AddTagsView,
        ContentTagsView,
        EditAddressView,
        ManifestDetailView,
        ManifestsView,
        MoveView,
        PartnersView,
        ScanInfoView,
        ScanKegsView,
        SearchedManifestsListView,
        SearchManifestsView,
        SearchPartnersView,
        ValidateBarcodeView,
        DashboardView,
        InventoryView,
        AddPalletsView,
        BatchView,
        FillView,
        FillScanView,
        SizeView,
        MaintainView,
        PalletizeView,
        AddBatchView,
    }
}
